### ISSUE TITLE
Environmental configuration issues

### ISSUE THREAD

**Issue by gaole1111** [jiaor17/DiffCSP#9]

**Comment by gaole1111** [comment]
(gl) root@ubuntu:/data2/gl/DiffCSP-main# python diffcsp/run.py data=perov_5 expname=reproduction_diffcsp_perov
diffcsp/run.py:172: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path=str(PROJECT_ROOT / "conf"), config_name="default")
/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'default': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
Global seed set to 42
[2024-03-06 20:05:23,548][hydra.utils][INFO] - Instantiating <diffcsp.pl_data.datamodule.CrystDataModule>
Error executing job with overrides: ['data=perov_5', 'expname=reproduction_diffcsp_perov']
Traceback (most recent call last):
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'diffcsp.pl_data' has no attribute 'datamodule'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/data1/anaconda3/envs/gl/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data2/gl/DiffCSP-main/./diffcsp/pl_data/datamodule.py", line 15, in <module>
    from diffcsp.common.data_utils import get_scaler_from_data_list
  File "/data2/gl/DiffCSP-main/./diffcsp/common/data_utils.py", line 8, in <module>
    from pymatgen.core.structure import Structure
ModuleNotFoundError: No module named 'pymatgen.core'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'diffcsp.pl_data.datamodule.CrystDataModule':
ModuleNotFoundError("No module named 'pymatgen.core'")
Are you sure that 'datamodule' is importable from module 'diffcsp.pl_data'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "diffcsp/run.py", line 178, in <module>
    main()
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "diffcsp/run.py", line 174, in main
    run(cfg)
  File "diffcsp/run.py", line 93, in run
    datamodule: pl.LightningDataModule = hydra.utils.instantiate(
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'diffcsp.pl_data.datamodule.CrystDataModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: data.datamodule

**Comment by jiaor17** [comment]
Hi, it seems like the `pymatgen` package is not installed in your current environment, according to the error:
```
ModuleNotFoundError: No module named 'pymatgen.core'
```
You could install it by 
```
pip install pymatgen==2022.9.21
```

**Comment by jiaor17** [comment]
Hi, we find that downloading the `2022.9.21` version of `pymatgen` via pip would encounter an error now. An available and compatible version is `2023.8.10`. You could try again with 
```
pip install pymatgen==2023.8.10
```

Thanks quite a lot for pointing out the problem!

**Comment by gaole1111** [comment]
Hi，I have a new question，
(gl) root@ubuntu:/data2/gl/DiffCSP-main# python diffcsp/run.py data=perov_5 expname=test1
diffcsp/run.py:172: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path=str(PROJECT_ROOT / "conf"), config_name="default")
/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'default': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/data1/anaconda3/envs/gl/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
Global seed set to 42
[2024-03-08 10:55:41,990][hydra.utils][INFO] - Instantiating <diffcsp.pl_data.datamodule.CrystDataModule>
Segmentation fault

**Comment by gaole1111** [comment]
(gl) root@ubuntu:/data2/gl/DiffCSP-main# python diffcsp/run.py data=perov_5 expname=test1
Global seed set to 42
[2024-03-08 16:56:18,016][hydra.utils][INFO] - Instantiating <diffcsp.pl_data.datamodule.CrystDataModule>
Segmentation fault

**Comment by jiaor17** [comment]
Hi, could you please provide more details about your environment? This will help us reproduce the error and offer a solution. 

Could you export the minimal Conda environment leading to the segmentation fault and share it with us? You can do this by running the following command:

```
conda env export > env.yaml
```

Once you've done that, please paste the contents of `env.yaml` here. With this information, we'll be better equipped to diagnose and resolve the problem you're facing.

**Comment by gaole1111** [comment]
python==3.8.13
torch==1.9.0
torch-geometric==1.7.2
pytorch_lightning==1.3.8
pymatgen==2022.9.21

**Comment by gaole1111** [comment]
name: gl
channels:
  - https://repo.anaconda.com/pkgs/main
  - pytorch
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.5.18.1=py38h06a4308_0
  - cffi=1.15.0=py38hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - decorator=5.1.1=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - icu=68.1=h2531618_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jedi=0.18.1=py38h578d9bd_1
  - jpeg=9d=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1o=h7f8727e_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.0.1=py38h22f2fdc_0
  - prompt-toolkit=3.0.29=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - python_abi=3.8=2_cp38
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - sqlite=3.38.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - traitlets=5.2.1.post0=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - xeus=1.0.4=h7d0c39e_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.15.0
    - accelerate==0.12.0
    - aiofiles==0.8.0
    - aiohttp==3.7.4
    - aiosignal==1.2.0
    - albumentations==1.1.0
    - alembic==1.12.1
    - altair==4.2.0
    - amqp==5.1.1
    - analytics-python==1.4.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.6.1
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.2
    - asgiref==3.5.2
    - astor==0.8.1
    - asttokens==2.0.5
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - attrs==21.4.0
    - autopage==0.5.2
    - azure-core==1.22.1
    - azure-eventhub==5.1.0
    - azure-storage-blob==12.6.0
    - babel==2.10.1
    - backoff==1.10.0
    - backports-zoneinfo==0.2.1
    - bcrypt==3.2.2
    - beautifulsoup4==4.11.1
    - billiard==3.6.4.0
    - binaryornot==0.4.4
    - black==22.3.0
    - bleach==5.0.0
    - blessings==1.7
    - blinker==1.5
    - boltons==21.0.0
    - boto==2.49.0
    - boto3==1.23.10
    - botocore==1.26.10
    - brotli==1.0.9
    - build==1.1.1
    - cachecontrol==0.14.0
    - cachetools==5.0.0
    - celery==5.1.2
    - chardet==3.0.4
    - clang==5.0
    - cleo==2.1.0
    - click==8.1.3
    - click-didyoumean==0.3.0
    - click-plugins==1.1.1
    - click-repl==0.2.0
    - cliff==4.6.0
    - clip==1.0
    - cloudpickle==2.1.0
    - cmaes==0.10.0
    - cmd2==2.4.3
    - colorama==0.4.4
    - coloredlogs==15.0.1
    - colorlog==6.7.0
    - commonmark==0.9.1
    - configparser==5.2.0
    - cookiecutter==1.7.3
    - crashtest==0.4.1
    - cryptography==36.0.1
    - ctgan==0.8.0
    - curtsies==0.3.10
    - cwcwidth==0.1.6
    - cycler==0.11.0
    - cython==0.29.30
    - dask==2.6.0
    - data==0.4
    - datasets==2.6.1
    - debugpy==1.6.0
    - defusedxml==0.7.1
    - deprecated==1.2.13
    - diffusers==0.7.0.dev0
    - dill==0.3.8
    - distlib==0.3.8
    - django==3.2
    - django-cors-headers==3.12.0
    - django-extensions==3.1.5
    - django-http-exceptions==1.4.0
    - django-model-utils==4.2.0
    - django-request-logging==0.7.5
    - djangorestframework==3.13.1
    - dm-tree==0.1.7
    - docker-pycreds==0.4.0
    - drf-jwt==1.13.4
    - dulwich==0.21.7
    - einops==0.5.0
    - einops-exts==0.0.3
    - ema-pytorch==0.0.10
    - emmet-core==0.68.0
    - emoji==2.2.0
    - entrypoints==0.4
    - et-xmlfile==1.1.0
    - executing==0.8.3
    - faker==19.13.0
    - fastapi==0.68.0
    - fastjsonschema==2.19.1
    - ffmpy==0.3.0
    - filelock==3.13.1
    - fire==0.4.0
    - flask==2.0.2
    - flask-compress==1.9.0
    - flask-cors==3.0.10
    - flatbuffers==1.12
    - flower==1.0.0
    - fonttools==4.31.2
    - frozenlist==1.3.0
    - fsspec==2024.2.0
    - ftfy==6.1.1
    - funcsigs==1.0.2
    - future==0.18.2
    - gast==0.3.3
    - gdown==4.5.3
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googledrivedownloader==0.4
    - gputil==1.4.0
    - gradio==2.9.4
    - greenlet==1.1.2
    - grpcio==1.32.0
    - gym==0.20.0
    - gym-unity==0.28.0
    - h11==0.13.0
    - h5py==2.10.0
    - hdbscan==0.8.28
    - huggingface-hub==0.21.3
    - humanfriendly==10.0
    - humanize==4.1.0
    - hydra-core==1.1.1
    - hydra-optuna-sweeper==1.1.0
    - imageio==2.19.3
    - imageio-ffmpeg==0.4.3
    - imagen-pytorch==1.11.12
    - importlib-metadata==7.0.1
    - importlib-resources==5.7.1
    - installer==0.7.0
    - invisible-watermark==0.1.5
    - ipykernel==6.13.0
    - ipython==8.3.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - isodate==0.6.1
    - isort==5.10.1
    - itsdangerous==2.1.2
    - jaraco-classes==3.3.1
    - jeepney==0.8.0
    - jinja2==3.0.3
    - jinja2-time==0.2.0
    - jmespath==1.0.0
    - joblib==1.1.0
    - json5==0.9.8
    - jsonschema==4.5.1
    - jupyter==1.0.0
    - jupyter-client==7.3.1
    - jupyter-console==6.4.4
    - jupyter-core==4.10.0
    - jupyter-kite==2.0.2
    - jupyter-lsp==1.5.1
    - jupyter-resource-usage==0.6.1
    - jupyter-server==1.17.0
    - jupyterlab==3.4.2
    - jupyterlab-drawio==0.9.0
    - jupyterlab-execute-time==2.1.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.13.0
    - jupyterlab-system-monitor==0.8.0
    - jupyterlab-topbar==0.6.1
    - jupyterlab-widgets==1.1.0
    - jupyterthemes==0.20.0
    - jupytext==1.13.8
    - kaptan==0.5.12
    - keras==2.11.0
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - keras-unet-collection==0.1.10
    - keras2onnx==1.7.0
    - keyring==24.3.1
    - kiwisolver==1.4.2
    - kombu==5.2.4
    - kornia==0.6.7
    - latex==0.7.0
    - latexcodec==2.0.1
    - lesscpy==0.15.0
    - libclang==14.0.6
    - libtmux==0.11.0
    - lightgbm==4.1.0
    - lightning-utilities==0.10.1
    - linkify-it-py==1.0.3
    - llvmlite==0.38.1
    - lmdb==1.3.0
    - locket==1.0.0
    - mako==1.3.0
    - markdown==3.3.6
    - markdown-it-py==2.1.0
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - mdit-py-plugins==0.3.0
    - mdurl==0.1.1
    - mistune==0.8.4
    - mixpanel==4.7.0
    - mizani==0.7.4
    - mlagents-envs==0.28.0
    - modelcards==0.1.6
    - monotonic==1.6
    - monty==2023.9.25
    - more-itertools==8.13.0
    - mp-api==0.35.1
    - mpmath==1.2.1
    - msgpack==1.0.8
    - msrest==0.6.21
    - multidict==6.0.2
    - multiprocess==0.70.16
    - mypy-extensions==0.4.3
    - nbclassic==0.3.7
    - nbclient==0.6.3
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==3.1
    - ninja==1.11.1
    - nltk==3.8.1
    - nodejs==0.1.1
    - notebook==6.4.11
    - notebook-shim==0.1.0
    - npm==0.1.1
    - ntfy==2.7.0
    - numba==0.55.2
    - numpy==1.24.4
    - oauthlib==3.2.0
    - omegaconf==2.3.0
    - onnx==1.9.0
    - onnxconverter-common==1.9.0
    - onnxruntime==1.13.1
    - opencv-python==4.5.5.64
    - opencv-python-headless==4.6.0.66
    - openpyxl==3.1.2
    - opt-einsum==3.3.0
    - optional-django==0.1.0
    - optuna==2.4.0
    - orjson==3.6.8
    - p-tqdm==1.4.0
    - packaging==23.2
    - palettable==3.3.0
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - paramiko==2.11.0
    - partd==1.2.0
    - pathlib==1.0.1
    - pathos==0.3.2
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pathvalidate==2.5.0
    - patsy==0.5.2
    - pbr==6.0.0
    - perceptilabs==0.13.21
    - pip==24.0
    - pkginfo==1.10.0
    - platformdirs==4.2.0
    - plotly==5.19.0
    - plotnine==0.9.0
    - ply==3.11
    - poetry==1.8.2
    - poetry-core==1.9.0
    - poetry-plugin-export==1.6.0
    - pox==0.3.4
    - poyo==0.5.0
    - ppft==1.7.6.8
    - prettytable==3.10.0
    - prometheus-client==0.14.1
    - promise==2.3
    - protobuf==3.19.6
    - psutil==5.9.0
    - psycopg2-binary==2.9.3
    - ptvsd==4.3.2
    - pudb==2022.1.2
    - pure-eval==0.2.2
    - pyarrow==9.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybtex==0.24.0
    - pycryptodome==3.14.1
    - pydantic==1.10.14
    - pydeck==0.8.0b4
    - pydeprecate==0.3.0
    - pydub==0.25.1
    - pygithub==1.54.1
    - pyjwt==1.7.1
    - pymatgen==2023.8.10
    - pympler==1.0.1
    - pynacl==1.5.0
    - pyparsing==3.0.7
    - pyperclip==1.8.2
    - pyproject==1.3.1
    - pyproject-hooks==1.0.0
    - pyrsistent==0.18.1
    - pyspng==0.1.1
    - python-dateutil==2.8.2
    - python-dotenv==1.0.1
    - python-louvain==0.16
    - python-multipart==0.0.5
    - python-slugify==6.1.2
    - pytorch-fid==0.2.1
    - pytorch-lightning==1.3.8
    - pytorch-warmup==0.1.0
    - pytz==2022.1
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.3.0
    - pyyaml==5.4.1
    - pyzmq==22.3.0
    - qtconsole==5.3.1
    - qtpy==2.1.0
    - qudida==0.0.4
    - rapidfuzz==3.6.2
    - rdflib==7.0.0
    - rdt==1.9.0
    - redis==3.5.3
    - regex==2022.9.13
    - requests-oauthlib==1.3.1
    - requests-toolbelt==1.0.0
    - responses==0.18.0
    - retrying==1.3.3
    - rich==12.6.0
    - rsa==4.8
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - s3transfer==0.5.2
    - sacremoses==0.0.53
    - safetensors==0.4.2
    - scikit-image==0.17.2
    - scikit-learn==1.1.1
    - scipy==1.8.0
    - seaborn==0.11.2
    - secretstorage==3.3.3
    - semver==2.13.0
    - send2trash==1.8.0
    - sentencepiece==0.1.97
    - sentry-sdk==1.5.10
    - setproctitle==1.2.3
    - setuptools==59.5.0
    - shap==0.40.0
    - shellingham==1.5.4
    - shortuuid==1.0.8
    - shutilwhich==1.1.0
    - six==1.15.0
    - slicer==0.0.7
    - smmap==5.0.0
    - sniffio==1.2.0
    - soupsieve==2.3.2.post1
    - spglib==2.3.1
    - sqlalchemy==2.0.23
    - sqlparse==0.4.2
    - stack-data==0.2.0
    - stanza==1.4.2
    - starlette==0.14.2
    - statsmodels==0.13.2
    - stevedore==5.2.0
    - streamlit==1.14.0
    - subprocess32==3.5.4
    - sympy==1.11.1
    - tabulate==0.9.0
    - taming-transformers==0.0.1
    - tblib==1.7.0
    - tempdir==0.7.1
    - tenacity==8.2.3
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-addons==0.13.0
    - tensorflow-estimator==2.4.0
    - tensorflow-gpu==2.4.0
    - tensorflow-hub==0.12.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - termcolor==1.1.0
    - terminado==0.15.0
    - test-tube==0.7.5
    - text-unidecode==1.3
    - tf-slim==1.1.0
    - tf2onnx==1.7.2
    - theme-darcula==3.1.1
    - threadpoolctl==3.1.0
    - tifffile==2022.3.25
    - timm==0.3.4
    - tinycss2==1.1.1
    - tmuxp==1.11.1
    - tokenizers==0.15.2
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.12.4
    - toolz==0.11.2
    - torch==1.9.0
    - torch-geometric==1.7.2
    - torch-scatter==2.1.2
    - torch-sparse==0.6.18
    - torchaudio==0.12.0+cu116
    - torchmetrics==0.5.0
    - torchvision==0.13.0+cu116
    - tornado==6.1
    - tqdm==4.64.0
    - transformers==4.38.2
    - trove-classifiers==2024.3.3
    - typeguard==2.13.3
    - typing-extensions==4.10.0
    - tzdata==2022.6
    - tzlocal==4.2
    - uamqp==1.5.3
    - uc-micro-py==1.0.1
    - umap==0.1.1
    - uncertainties==3.1.7
    - urllib3==1.25.10
    - urwid==2.1.2
    - urwid-readline==0.13
    - uvicorn==0.15.0
    - validators==0.20.0
    - vine==5.0.0
    - virtualenv==20.25.1
    - waitress==2.0.0
    - wandb==0.12.15
    - warmup-scheduler==0.3
    - watchdog==2.1.9
    - webencodings==0.5.1
    - websocket-client==1.3.2
    - websockets==10.3
    - werkzeug==2.0.3
    - wget==3.2
    - wheel==0.42.0
    - widgetsnbextension==3.6.0
    - wrapt==1.12.1
    - xeus-python==0.13.7
    - xeus-python-shell==0.2.0
    - xxhash==3.1.0
    - yarl==1.7.2
    - yarn==1.0.0
    - zipp==3.8.0
prefix: /data1/anaconda3/envs/gl

**Comment by gaole1111** [comment]
Thank you for your reply. We are running the command here, as shown in the above results

**Comment by yuuhaixia** [comment]
> (gl) root@ubuntu:/data2/gl/DiffCSP-main# python diffcsp/run.py data=perov_5 expname=test1 Global seed set to 42 [2024-03-08 16:56:18,016][hydra.utils][INFO] - Instantiating <diffcsp.pl_data.datamodule.CrystDataModule> Segmentation fault

I have the same problem as you, have you solved it and can you reply me, thanks a lot!
